# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['vendor', '/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# TODO: Add Google Analytics
# Site Settings
title: "Science Policy and the Public in Italy"
email: "spp2019.cambridge@gmail.com"
description: ""
baseurl: "/conference"
url: "https://spp2019.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "" #TODO
googleAnalyticsSiteUrl: "spp2019.github.io"
siteVerification: "" #TODO

# Organizer Info
organizerName: "SPP"
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: "spp2019.cambridge@gmail.com"
organizerLogo: ""
organizerLink: ""

# Head
metaKeywords: "science, policy, research, public, Italy, UK"
twitterAccount: "" #TODO
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# link al google doc (per call for posters)
c4pUrl: "" 
#"https://goo.gl/forms/Gt6H2bYdD0xSncHF2"
# go to pdf "how to become sponsor"
c4sponsorsUrl: "/assets/SPP_Italy_sponsorship_new.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#about", text: "About"}
 - {permalink: "/schedule/", text: "Programme"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Committee"}
# - {link: "https://goo.gl/forms/Gt6H2bYdD0xSncHF2", text: "Call for Posters"}
 - {permalink: "/#venue", text: "Venue"}

bottomNavigationLinks:
 - {permalink: "/assets/SPP_Italy_sponsorship_new.pdf", text: "Become a Sponsor"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Register"}

# Hero Block
heroImage: "/kings.jpg"
heroTitle: "SPP <typeout> 2019"
eventDate: "Saturday 26th October 2019"
typeoutTextValues: '"", "Science ", "Policy ", "Public "'
typeoutFallback: ""
heroButtons:
 - {permalink: "/#tickets", text: "Register"} # TODO
# - {link: "https://goo.gl/forms/Gt6H2bYdD0xSncHF2", text: "Submit a poster"}
 - {permalink: "/assets/SPP_Italy_sponsorship.pdf", text: "Become a sponsor"}

# About Block
aboutTitle: "About"

aboutBlock:
# intro su conf
#{text: "Our society today faces unprecedented challenges, including the need for affordable and sustainable energy, "}

 # qui spieghiamo i temi
 - {title: "Energy and the environment<br><br>", image: "energy.jpg", text: "renewable energy, green transport technologies, smart cities, sustainable manufacturing" }
 - {title: "Public Health and Biotechnology", image: "biotech.jpg", text: "gene editing, stem cells and regenerative medicine" }
 - {title: "Digital technologies<br><br>", image: "hackathon.jpg", text: "deep learning and artificial intelligence, pervasive computing, social and digital media" }

aboutBlock2:
 # qui spieghiamo i temi
 - {title: "Talks", image: "conference.jpg", text: "Invited speakers will provide their perspective on key policy issues" }
 - {title: "Panels", image: "panel.jpg", text: "Speakers will engage in debates on scientific research, policymaking, and the public opinion" }
 - {title: "Posters", image: "poster.jpg", text: "Young researchers will present research evidence to policymakers" }
 - {title: "Networking", image: "workshop.jpg", text: "Participants will meet with science and technology companies and researchers" }


# Statistic Block
#statisticBlockImage: "statistic.jpg"
#statisticBlock:
# - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
# - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
# - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
# - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
#latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "clare.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "St John's College"
eventLocationLink: "https://www.joh.cam.ac.uk/"
eventStreetAddress: "St Johns St"
eventAddressLocality: "Cambridge"
eventAddressLocalityRegion: "Cambridgeshire"
eventPostalCode: "CB2 1TP"
eventAddressCountry: "United Kingdom"
eventStartTime: "2019-10-26T10:00"
eventDoorTime: "09:00"
eventEndTime: "2019-10-26T20:00"
eventPlaceCoordinates: "52.207899, 0.118436"
mapCenterCoordinates: "52.207899, 0.118436"
mapMobileCenterCoordinates: "52.207899, 0.118436"

# Venue Block
venueBlockTitle: "Venue"

venueBigImage: "ods_interno_1.jpg"
venueSmallImage1: "ods.jpg"
venueSmallImage2: "ods_lighfoot.jpg"
#ods_interni.jpg"
venueSmallImage3: "ods_lighfoot.jpg"
venueTitle: "Old Divinity School"
venueFeatures: ["180-seat Lecture Theatre", "Central Hall for refreshments & posters", "Auxiliary rooms for company stands"]

# TODO Add Twitter feed
# Tweets Feed Block
tweetsFeedImage: "twitter.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "spp2019"
twitterFeed: "" # TODO

# Partners Block
organizersTitle: "Organisers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# TODO Add subscribe action to MailChimp mailing list
# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://eepurl.com/gkpERj"
subscribeInfo: "Registration will be open soon. Tickets are limited in number. Stay tuned!"

# TODO Add Eventbrite link
# Tickets Block
ticketsTitle: "Register"
ticketsInfo: "Tickets are free and grant access to all conference sections, coffee brakes, and lunch. Accommodation is NOT included in the ticket."
ticketsOffers:
 -
  name: ""
  price: ""
  priceCurrency: ""
  ticketsNumber: "180"
  buyButtonLink: "" # TODO
  buyButtonText: "Coming soon"
  ticketContentList: ["SPP 2019 Cambridge Symposium"]
  validFrom: "2019-04-01T10:00"
  validThrough: "2019-10-25T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.cuitaliansociety.org.uk/", text: "Cambridge University Italian Society"}
   - {link: "https://www.aisuk.org/", text: "Association of Italian Scientists in the UK"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:spp2019.cambridge@gmail.com", text: "spp2019.cambridge@gmail.com"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: ""
#About us"
aboutUs: "SPP Italy 2019 is organised by a group of PhD students and researchers who wish to improve the interaction between academics, policymakers and science communicators. If you would like to talk to us about anything (collaborations, sponsorship, ideas), do not hesitate to get in touch!"
#We are a group of Italian PhD students and researchers located in Cambridge and London. We hope that the interaction of researchers, science communicators and policymakers, fundamental to a modern functioning democracy, will help formulating innovative ideas to develop an adequate role for scientific expertise and evidence in democratic deliberation."

# Logistics Find Way Block
#findWayTitle: "Find your way here"
#findWayDistance: "Distance"
#findWayDriving: "DRIVING"
#findWayWalking: "WALKING"
#findWayBicycling: "BICYCLING"
#findWayTransit: "TRANSIT"
#findWayFindFlight: "Find Flight"
#logisticsMapCenterCoordinates: "49.056728, 3.117289"
#logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
#logisticsMapAutoDirections: false

# Logistics Direction Details Block
#directionDetailsImage: "direction-details.jpg"
#directionDetailsTitle: "Get around Lviv"
#directionDetailsCards:
# - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
# - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
# - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
#directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"

theme: jekyll-theme-cayman